version: '3'
services:

  postgresql:
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=meta_wallet
    networks:
      - app-network
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    image: postgres

  app-metawallet:
    image: app-metawallet
    container_name: app-metawallet-container
    depends_on:
      - postgresql
    environment:
      - HOST_DB=postgresql
      - PORT_DB=5432
      - APP_PORT=8090
      - DB_NAME=meta_wallet
      - USERNAME_DB=postgres
      - PASSWORD_DB=123
    ports:
      - "8080:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
